Repository ISIS3510-202320-Team21/flutter_sports_app, pull requests merged in 2023-11, with the labels that each got.

#49 Sprint 3: connectivity issues requested and new functionality fixed
  lib/data/repositories/match_repository.dart
  lib/logic/blocs/connectivity/bloc/connectivity_bloc.dart
  lib/logic/blocs/connectivity/bloc/connectivity_event.dart
  lib/logic/blocs/connectivity/bloc/connectivity_state.dart
  lib/logic/blocs/match/bloc/match_bloc.dart
  lib/logic/blocs/match/bloc/match_event.dart
  lib/logic/blocs/match/bloc/match_state.dart
  lib/main.dart
  lib/presentation/screens/MainLayout.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/screens/match/my_matches.dart
  lib/presentation/screens/match/new_matches_view.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/match/sport_match_options_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: bug, enhancement

#50 Update backend and fix navigation in MainLayout
  .env
  lib/main.dart
  lib/presentation/screens/MainLayout.dart
  pubspec.lock
Labels: bug

#51 Add navigation event to GlobalBloc
  lib/presentation/screens/MainLayout.dart
Labels: bug

#52 Update notification button text in home view
  lib/presentation/screens/home_view.dart
Labels: enhancement

#53 Add dependencies and bloc for fetching data
  lib/data/models/notification.dart
  lib/data/models/user.dart
  lib/logic/blocs/authentication/bloc/authentication_bloc.dart
  lib/logic/blocs/authentication/bloc/authentication_event.dart
  lib/logic/blocs/authentication/bloc/authentication_state.dart
  lib/logic/blocs/fetch/bloc/fetch_bloc.dart
  lib/logic/blocs/fetch/bloc/fetch_event.dart
  lib/logic/blocs/fetch/bloc/fetch_state.dart
  lib/main.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/screens/signUp_view.dart
  lib/presentation/widgets/WeatherDisplay.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#54 Refactor navigation logic in MainLayout.dart
  lib/presentation/screens/MainLayout.dart
Labels: bug, enhancement

#55 Eventual connectivity implemented, cache images and new features
  lib/data/models/notification.dart
  lib/data/models/sport.dart
  lib/data/models/user.dart
  lib/data/repositories/auth_repository.dart
  lib/data/repositories/sport_repository.dart
  lib/data/repositories/user_repository.dart
  lib/logic/blocs/authentication/bloc/authentication_bloc.dart
  lib/logic/blocs/authentication/bloc/authentication_event.dart
  lib/logic/blocs/home/bloc/home_bloc.dart
  lib/logic/blocs/home/bloc/home_event.dart
  lib/logic/blocs/sport/bloc/bloc/sport_bloc.dart
  lib/logic/blocs/sport/bloc/bloc/sport_event.dart
  lib/main.dart
  lib/presentation/screens/MainLayout.dart
  lib/presentation/screens/camera_view.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/screens/login_view.dart
  lib/presentation/screens/match/matches_view.dart
  lib/presentation/screens/match/my_matches.dart
  lib/presentation/screens/match/new_matches_view.dart
  lib/presentation/screens/match/sport_match_options_view.dart
  lib/presentation/screens/profile_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#56 Profile photo added
  lib/presentation/screens/profile_view.dart
  lib/presentation/widgets/WeatherDisplay.dart
  pubspec.lock
Labels: bug, enhancement

#57 bugs fixed in all views, now you can rate matches, real time profile updated.
  .env
  android/app/build.gradle
  lib/data/models/match.dart
  lib/data/repositories/auth_repository.dart
  lib/data/repositories/match_repository.dart
  lib/logic/blocs/authentication/bloc/authentication_bloc.dart
  lib/logic/blocs/camera/bloc/camera_bloc.dart
  lib/logic/blocs/camera/bloc/camera_state.dart
  lib/logic/blocs/edit_profile/bloc/edit_profile_bloc.dart
  lib/logic/blocs/edit_profile/bloc/edit_profile_state.dart
  lib/logic/blocs/fetch/bloc/fetch_bloc.dart
  lib/logic/blocs/fetch/bloc/fetch_event.dart
  lib/logic/blocs/fetch/bloc/fetch_state.dart
  lib/logic/blocs/match/bloc/match_bloc.dart
  lib/logic/blocs/match/bloc/match_event.dart
  lib/logic/blocs/match/bloc/match_state.dart
  lib/logic/blocs/profile/profile_bloc.dart
  lib/logic/blocs/profile/profile_event.dart
  lib/logic/blocs/profile/profile_state.dart
  lib/main.dart
  lib/presentation/screens/camera_view.dart
  lib/presentation/screens/editProfile_view.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/screens/match/individual_match.dart
  lib/presentation/screens/match/my_matches.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/match/sport_match_options_view.dart
  lib/presentation/screens/profile_view.dart
  lib/presentation/screens/signUp_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#58 Update code with new IP address and remove unused and async problems solved
  .env
  lib/logic/blocs/match/bloc/match_state.dart
  lib/main.dart
  lib/presentation/screens/match/individual_match.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/match/sport_match_options_view.dart
Labels: enhancement

#59 bug fixes, Sprint 3 and Preparation Sprint 4
  .env
  lib/data/models/match.dart
  lib/data/repositories/match_repository.dart
  lib/presentation/screens/editProfile_view.dart
  lib/presentation/screens/match/my_matches.dart
  lib/presentation/screens/match/new_matches_view.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/match/sport_match_options_view.dart
  lib/presentation/screens/profile_view.dart
Labels: bug, enhancement

#60 Add fl_chart dependency and update MainLayout with
  lib/logic/blocs/statistics/statistic_bloc.dart
  lib/logic/blocs/statistics/statistic_event.dart
  lib/logic/blocs/statistics/statistic_state.dart
  lib/presentation/screens/MainLayout.dart
  lib/presentation/screens/basic_statistics_view.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/widgets/CustomBottomNavigationBar.dart
  lib/xd.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, documentation

#61 bug - edit profile.
  lib/main.dart
  lib/presentation/screens/editProfile_view.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/screens/match/individual_match.dart
  lib/presentation/screens/match/matches_view.dart
  lib/presentation/screens/match/my_matches.dart
  lib/presentation/screens/match/new_matches_view.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/match/sport_match_options_view.dart
  lib/presentation/screens/profile_view.dart
  lib/presentation/widgets/CustomBottomNavigationBar.dart
  lib/xd.dart
Labels: bug, documentation

#62 Fixed bugs and already in well state.
  .env
  devtools_options.yaml
  lib/data/models/level.dart
  lib/data/models/match.dart
  lib/data/repositories/match_repository.dart
  lib/main.dart
  lib/presentation/screens/MainLayout.dart
  lib/presentation/screens/basic_statistics_view.dart
  lib/presentation/screens/camera_view.dart
  lib/presentation/screens/editProfile_view.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/screens/login_view.dart
  lib/presentation/screens/match/individual_match.dart
  lib/presentation/screens/match/my_matches.dart
  lib/presentation/screens/match/new_matches_view.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/match/sport_match_options_view.dart
  lib/presentation/screens/profile_view.dart
  lib/presentation/screens/signUp_view.dart
Labels: bug, documentation, duplicate
