Repository ISIS3510-202320-Team21/flutter_sports_app, pull requests merged in 2023-12, with the labels that each got.

#63 ECS fixed
  .vscode/settings.json
  lib/main.dart
  lib/presentation/screens/editProfile_view.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/match/sport_match_options_view.dart
  lib/presentation/screens/signUp_view.dart
Labels: bug, enhancement, help wanted

#64 Bug fixing
  lib/presentation/screens/profile_view.dart
Labels: bug

#66 Fix connectivity issue and load weather data
  .env
  lib/presentation/screens/home_view.dart
Labels: enhancement

#68 Add claim submission UI
  lib/presentation/screens/claims_view.dart
Labels: enhancement

#69 app bar update
  lib/presentation/screens/claims_view.dart
  lib/presentation/screens/editProfile_view.dart
  lib/presentation/screens/login_view.dart
  lib/presentation/screens/signUp_view.dart
Labels: bug, duplicate

#72 statistics feature and ECN added, local storage pending...
  lib/data/models/classes.dart
  lib/data/repositories/user_repository.dart
  lib/logic/blocs/statistics/statistic_bloc.dart
  lib/logic/blocs/statistics/statistic_event.dart
  lib/logic/blocs/statistics/statistic_state.dart
  lib/main.dart
  lib/presentation/screens/basic_statistics_view.dart
  lib/presentation/screens/camera_view.dart
  lib/presentation/screens/claims_view.dart
  lib/presentation/screens/home_view.dart
  lib/presentation/screens/match/prefered_match.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
  windows/flutter/CMakeLists.txt
Labels: bug, enhancement

#76 statistic feature and ECN updated and now running
  lib/data/models/classes.dart
  lib/logic/blocs/statistics/statistic_bloc.dart
  lib/logic/blocs/statistics/statistic_event.dart
  lib/logic/blocs/statistics/statistic_state.dart
  lib/main.dart
  lib/presentation/screens/basic_statistics_view.dart
  lib/presentation/screens/match/prefered_match.dart
Labels: enhancement

#77 Microptimizations added
  .env
  lib/data/models/match.dart
  lib/logic/blocs/fetch/bloc/fetch_bloc.dart
  lib/logic/blocs/fetch/bloc/fetch_event.dart
  lib/logic/blocs/fetch/bloc/fetch_state.dart
  lib/logic/blocs/statistics/statistic_bloc.dart
  lib/logic/blocs/statistics/statistic_event.dart
  lib/logic/blocs/statistics/statistic_state.dart
  lib/presentation/screens/MainLayout.dart
  lib/presentation/screens/basic_statistics_view.dart
  lib/presentation/screens/login_view.dart
  lib/presentation/screens/match/prefered_match.dart
  lib/presentation/screens/profile_view.dart
  lib/presentation/screens/signUp_view.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#79 Cleaned code
  lib/data/repositories/auth_repository.dart
  lib/logic/blocs/camera/bloc/camera_bloc.dart
  lib/logic/blocs/edit_profile/bloc/edit_profile_bloc.dart
  lib/logic/blocs/global_events/bloc/global_bloc.dart
  lib/logic/blocs/match/bloc/match_bloc.dart
  lib/presentation/screens/editProfile_view.dart
  lib/presentation/screens/match/individual_match.dart
  lib/presentation/screens/profile_view.dart
Labels: enhancement

#80 deleted unused loc
  lib/logic/blocs/home/bloc/home_bloc.dart
  lib/logic/blocs/notification/bloc/notification_bloc.dart
  lib/presentation/screens/camera_view.dart
  lib/presentation/screens/login_view.dart
  lib/presentation/screens/match/matches_view.dart
Labels: enhancement

#81 Claims functionality updated
  lib/logic/blocs/claims/bloc/claims_bloc.dart
  lib/logic/blocs/claims/bloc/claims_event.dart
  lib/logic/blocs/claims/bloc/claims_state.dart
  lib/main.dart
  lib/presentation/screens/claims_view.dart
  lib/presentation/screens/home_view.dart
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
Labels: bug, enhancement
